BakeryShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add-item/<int:id_item>/', add_item, name='add_item'),
    path('minus-item/<int:id_item>/', minus_item,name='minus_item'),
    path('remove-item<int:id_item>/', remove_item, name='remove_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('decrement_ajax/', decrement_ajax, name="decrement_ajax"),
    path('increment_ajax/', increment_ajax, name="increment_ajax"),
    path('delete_ajax/', delete_ajax, name='delete_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.PositiveIntegerField(default=1)  
    description = models.TextField()
    price = models.IntegerField()
    date_added =  models.DateField(auto_now_add=True, name="date_added")
    image_url= models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import item

class ProductForm(ModelForm):
    class Meta:
        model = item
        fields = ["name", "amount", "description", "price", "image_url"]

main/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import item
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
import json


@login_required(login_url='/login')
def show_main(request):
    items = item.objects.filter(user=request.user)
    context = {
        'name': request.user.username,
        'class': 'PBP B',
        'items' : items,
        'last_login': request.COOKIES['last_login'],
        'total_items': items.__len__(),
    }
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
def show_json(request):
    data = item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
def show_xml_by_id(request, id):
    data = item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
def show_json_by_id(request, id):
    data = item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_item(request, id_item):
    product = get_object_or_404(item, pk=id_item, user=request.user)
    product.amount += 1
    product.save()
    return redirect('main:show_main')

def minus_item(request, id_item):
    product = get_object_or_404(item, pk=id_item, user=request.user)
    if product.amount >0:
        product.amount -= 1
        product.save()
    else: 
        messages.info(request, f'Tidak dapat mengurangi jumlah produk! Total {product.name} berjumlah 0 ')
    return redirect('main:show_main')

def remove_item(request, id_item):
    product = get_object_or_404(item, pk=id_item, user=request.user)
    product.delete()
    return redirect('main:show_main')

def get_product_json(request):
    product = item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        image_url = request.POST.get("image_url")
        user = request.user

        new_product = item(name=name, price=price, amount=amount ,description=description, image_url=image_url ,user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='login/')
@csrf_exempt
def increment_ajax(request):
    if request.method == 'POST':
        pk = json.loads(request.body).get('pk')
        product = item.objects.get(pk=pk, user=request.user)
        product.amount += 1
        product.save()
        return HttpResponse(b"OK", status=200)
    
    return HttpResponseNotFound()

@login_required(login_url='login/')
@csrf_exempt 
def decrement_ajax(request):
    if request.method == 'POST':
        pk = json.loads(request.body).get('pk')
        product = item.objects.get(pk=pk, user=request.user)
        if (product.amount > 0):
            product.amount -= 1
            product.save()
        else: # jika stok produk sudah habis = delete
            product.delete()
        return HttpResponse(b"OK", status=200)
    
    return HttpResponseNotFound()

@login_required(login_url='login/')
@csrf_exempt
def delete_ajax(request):
    if request.method == 'POST':
        pk = json.loads(request.body).get('pk')
        product = item.objects.get(pk=pk, user=request.user)
        product.delete()
        return HttpResponse(b"OK", status=200)
    
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<style>
    body{
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        text-align: center;
        background-image:url("https://i.pinimg.com/originals/ce/6a/6f/ce6a6f547ed740343a304abb4ef29ff7.gif");
        text-align: center;
    }
    .submit{
        background-color: #FFFFFF;
        border: 4px solid#6C3483;
        border-radius: 12px;
        box-sizing: border-box;
        color: #6C3483;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 15px;
        font-weight: 500;
        line-height: 20px;
        padding: 10px 15px;
    }
    input,
    textarea{
        margin-top: 5px;
        background-color: #FFFFFF;
        border: 2px solid#6C3483;
        border-radius: 8px;
        box-sizing: border-box;
        color: #6C3483;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 15px;
        font-weight: 500;
        line-height: 20px;
        padding: 5px 15px;
    }

   

    label{
        color:#6C3483;
    }
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
    <a class="navbar-brand" href="#" style="font-weight:500px;color:#6C3483;">BakeryShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#" style="color:#4f1964">{{name}}</a>
        <a class="nav-link active" aria-current="page" href="#" style="color:#4f1964">{{class}}</a>
        <a class="nav-link" href="{% url 'main:logout' %}" style="color: #BB8FCE;">Logout</a>
        </div>
    </div>
    </div>
</nav>


<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div  style="width:550px;height:840px;border-radius: 1rem; background-color:white;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h3 class="fw-bold mb-2 text-uppercase" style="color:#6C3483;padding-bottom: 27px;">Add New Item</h3>
              
              <form method="POST" >
    {% csrf_token %}
    <table>
      {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input class="submit" type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>
            
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    .heading{
        background-color: white;
        font-family: "Times New Roman", Times, serif;
        text-align:center ;
        font-style:italic;
    }

    body{
       
       background-image: url("https://i.pinimg.com/originals/ce/6a/6f/ce6a6f547ed740343a304abb4ef29ff7.gif");
       background-repeat: no-repeat;
       background-attachment: fixed;
       background-size: 100% 100%;
      }
    
</style>
<div class = "heading">
    <h1 style = "margin-left:10px;color:#6C3483">BakeryShop</h1>
    <p style="margin-left:10px;color:#BB8FCE">Fresh Baked Goods Everyday</p>
</div>

    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div  style="height:500px;border-radius: 1rem; background-color:white;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h3 class="fw-bold mb-2 text-uppercase" style="color:#6C3483">Login Page</h3>
                <p  style="color:#BB8FCE">Please enter your username and password!</p>

                <form method="POST" action="">
                    {% csrf_token %}
                    
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="typeEmailX">Input Username</label>
                            <input type="text" name="username" placeholder="Username" class="form-control">
                            
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="typePasswordX">Input Password</label>
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div>
                        <input class="btn login_btn" style="border-color: #6C3483; border-width: 3px;margin-top: 10px;" type="submit" value="Submit">
                        <p style="margin-top: 20px;margin-bottom: 20px;">  Don't have an account yet? <a href="{% url 'main:register' %}" style ="text-align: center;color:#4A235A">Register Now</a></p>
                </form>
              
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>

  
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li style="background-color:white ;">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
  

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}
<style>
    
    body{
       background-repeat: no-repeat;
       background-attachment: fixed;
       background-size: 100% 100%;
       text-align: center;
       background-image: url("https://i.pinimg.com/originals/ce/6a/6f/ce6a6f547ed740343a304abb4ef29ff7.gif");
    }

    #container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
        gap: 20px;
    }
    .card {
            
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        max-height:600px ;
        border-radius: 20px;
         
           
    }
    .button-23 {
        background-color: #FFFFFF;
        border: 1px solid#6C3483;
        border-radius: 7px;
        box-sizing: border-box;
        color: #6C3483;
        cursor: pointer;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 10px;
        font-weight: 500;
        line-height: 20px;
        outline: none;
        padding: 4px 12px;
        text-align: center;
        text-decoration: none;
        touch-action: manipulation;
        transition: box-shadow .2s,-ms-transform .1s,-webkit-transform .1s,transform .1s;
        user-select: none;
        -webkit-user-select: none;
        width: auto;
        display: inline-block; 
        position: relative;
    }
    .button-24{
        background-color: #FFFFFF;
        border: 4px solid#6C3483;
        border-radius: 12px;
        box-sizing: border-box;
        color: #6C3483;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 15px;
        font-weight: 500;
        line-height: 20px;
        padding: 15px 15px;
    }
    

</style>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
        <a class="navbar-brand" href="#" style="font-weight:500px;color:#6C3483;">BakeryShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="#" style="color:#4f1964">{{name}}</a>
            <a class="nav-link active" aria-current="page" href="#" style="color:#4f1964">{{class}}</a>
            <a class="nav-link" href="{% url 'main:logout' %}" style="color: #BB8FCE;">Logout</a>
            </div>
        </div>
        </div>
    </nav>
    <h2 style="color:#6C3483;text-align: center;padding-top: 35px;font-family: Times New Roman, Times, serif;font-style: italic;font-weight: 800;">Baked Goods </h2>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amounts:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="image_url" class="col-form-label">Image Url:</label>
                            <input type="text" class="form-control" id="image_url" name="image_url"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add_ajax" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <p>{{item}}</p>
    <div id="container"></div>

<script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            document.getElementById("container").innerHTML = "";
            const products = await getProducts()
            let htmlString = ``
            var counter = 1
            var size = Object.keys(products).length;
            products.forEach((item) => {
                htmlString += `\n
                <div style="margin-top:5px;padding: 10px;  padding-bottom: 8px;" class="card">
                <img style="max-height:300px;border-radius:20px;max-width: 500px;"class="card-img" src="${item.fields.image_url}" alt="Product Image"/>
                <h3 style="padding-top:10px;font-size: 24px; font-weight: 700;color:#552468;" >${item.fields.name}</h3>
                <p style="padding-top: 10px; font-size:19px; font-weight: 500;color:#6C3483" > ${item.fields.price}</p>
                <p style="font-size:16px; font-weight: 300;color: #BB8FCE;" > ${item.fields.description}</p>
                <div class="amount-container" style="margin-top: 10px;">
                    
                        <button class="button-23" style="margin-right: 3px;" method="POST" onclick="decrementAJAX(${item.pk})">-</button>
                
                    <span style="font-size: 12px;color:#552468;font-weight: 200px;">${item.fields.amount}</span>
                   
                        <button class="button-23" style="margin-left:3px ;" method="POST" onclick="incrementAJAX(${item.pk})">+</button>
                           
                </div>
                <div class="edit" style="justify-content: space-between;padding-top: 30px;" >
                    
                        <button class="button-23" style="margin-left: 3px;" method="POST" onclick="deleteAJAX(${item.pk})">
                            Remove Item
                        </button>
                  
                </div>
                <p style="padding-top:20px; font-size:10px; font-weight: 450;color:#552468;" > ${item.fields.date_added}</p>
                
            </div>`
        
            })

            document.getElementById("container").innerHTML = htmlString
        }

        refreshProducts()
        
        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        function incrementAJAX(pk) {
            fetch(`{% url 'main:increment_ajax' %}`, {
                method: "POST",
                body: JSON.stringify({
                    "pk":pk
                })
            }).then(refreshProducts)

            return false
        }

        function decrementAJAX(pk) {
            fetch(`{% url 'main:decrement_ajax' %}`, {
                method: "POST",
                body: JSON.stringify({
                    "pk":pk
                })
            }).then(refreshProducts)

            return false
        }

        function deleteAJAX(pk) {
            fetch(`{% url 'main:delete_ajax' %}`,  {
                method: "POST",
                body: JSON.stringify({
                    "pk":pk
                })
            }).then(refreshProducts)

            return false
        }
        document.getElementById("button_add_ajax").onclick = addProduct
</script>

<a href="{% url 'main:create_product' %}">
    <button class="button-24 "style="margin-top:14px;margin-bottom:10px;" >
        Add New Item
    </button>
</a>
<button class="button-24 "style="margin-top:14px;margin-bottom:10px;" type="button" class="btn btn-sm btn-outline mt-2 ml-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Product by AJAX
</button>
<h5 style="margin-top:12px;color:#6C3483;font-family: Times New Roman, Times, serif;font-weight: bold;">You Added {{total_items}} Baked Goods At The Bakery</h5>

<h5 style="margin-top:12px;color:#6C3483;font-family: Times New Roman, Times, serif;font-weight: bold;">Last Login Session: {{ last_login }}</h5>
  {% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
    .heading{
        background-color: white;
        font-family: "Times New Roman", Times, serif;
        text-align:center ;
        font-style:italic;
    }

    body{
        background-image: url("https://i.pinimg.com/originals/ce/6a/6f/ce6a6f547ed740343a304abb4ef29ff7.gif");
        text-align: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
       
      }
    .submit{
        background-color: #FFFFFF;
        border: 4px solid#6C3483;
        border-radius: 12px;
        box-sizing: border-box;
        color: #6C3483;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 15px;
        font-weight: 500;
        line-height: 20px;
        padding: 10px 15px;
    }
    input{
        margin-top: 5px;
        background-color: #FFFFFF;
        border: 2px solid#6C3483;
        border-radius: 8px;
        box-sizing: border-box;
        color: #6C3483;
        font-family: Circular,-apple-system,BlinkMacSystemFont,Roboto,"Helvetica Neue",sans-serif;
        font-size: 15px;
        font-weight: 500;
        line-height: 20px;
        padding: 5px 15px;
    }
    label{
        color:#6C3483;
    }
    
</style>
<div class = "heading">
    <h1 style = "color:#6C3483">BakeryShop</h1>
    <p style="color:#BB8FCE">Fresh Baked Goods Everyday</p>
</div>

<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div  style="height:680px;border-radius: 1rem; background-color:white;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h3 class="fw-bold mb-2 text-uppercase" style="color:#6C3483;padding-bottom: 27px;">Register Page</h3>
              
              <form method="POST" >  
          {% csrf_token %}  
          <table>  
              {{ form.as_table }}  
              <tr>  
                  <td></td>
                  <td><input class="submit" type="submit" name="submit" value="Daftar"/></td>  
              </tr>  
          </table>  
      </form>
            
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>



    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}